### ISSUE TITLE
Missing Task should fail linter

### ISSUE THREAD

**Issue by admiralAwkbar** [IBM/tekton-lint#20]
Hey All!

Im trying to add the `Tekton-lint` to the **GitHub Super-Linter** and have 1 ask for improvement.

Currently, if you run the following code:
```yml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: example-task-name
spec:
  params:
    - name: pathToDockerFile
      type: string
      description: The path to the dockerfile to build
      default: /workspace/workspace/Dockerfile
  resources:
    inputs:
      - name: workspace
        type: git
    outputs:
      - name: builtImage
        type: image
  steps:
    - name: ubuntu-example
      image: ubuntu
      args: ["ubuntu-build-example", "SECRETS-example.md"]
    - image: gcr.io/example-builders/build-example
      command: ["echo"]
      args: ["$(params.pathToDockerFile)"]
    - name: dockerfile-pushexample
      image: gcr.io/example-builders/push-example
      args: ["push", "$(resources.outputs.builtImage.url)"]
      volumeMounts:
        - name: example-volume
          mountPath: /var/run/docker.sock
  volumes:
    - name: example-volume
      emptyDir: {}
```

It will complete successfully with error code `0`

**But** if i remove the line:
```yml
kind: Task
```
It will run and show no output, and exit with exit code `0`... Can this be set to exit with error code if it fails to read the data?

thanks!
