### ISSUE TITLE
Add rule "no-deprecated"

### ISSUE THREAD

**Issue by necccc** [IBM/tekton-lint#22]
[Tekton CD TEP 003 suggests a deprecation label](https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md#deprecation--removal-strategy) be used on Resources that are to be marked as deprecated in a catalog.

Linter should watch for the label `tekton.dev/deprecated: true` and show a warning (or error if the user override the rule severity with their custom config).

Example for non-deprecated resource

```yaml
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: some-task
  labels:
    app.kubernetes.io/version: "1.0.3"
spec:

```

Example for a deprecated resource

```yaml
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: some-task
  labels:
    app.kubernetes.io/version: "1.0.3"
    tekton.dev/deprecated: true
spec:

```
