### ISSUE TITLE
Getting 'is already defined' errors when defined in different folders

### ISSUE THREAD

**Issue by johnmcevoy** [IBM/tekton-lint#4]
Hi there,

Just tried out your new lint tool (congrats!) and I got many errors like the following:
error   (4,9,4,20): 'ci-template' is already defined (as a 'TriggerTemplate')

The reason is that I've multiple folders containing tekton definitions and sometimes they have the same name used in another folder. This is fine for my use as my toolchains only pulls in one of these folders. Can we have a switch that only checks for dupe names within the same folder... maybe there already is?

**Comment by necccc** [comment]
You can create a `.tektonlintrc.yaml` in your working directory where you run the linter, and add custom rules, like

```yaml
---
rules:
  no-resource-redefine: "off" 

```

But currently, this is not documented, and there's a PR that fixes the rule override behavior of custom configs

**Comment by johnmcevoy** [comment]
Thanks, I tried that.. still get the redef but as warnings instead of errors.

**Comment by madbence** [comment]
@johnmcevoy I'd recommend executing the linter for each set of definitions. in k8s, resourced are identified by their `kind` + `name`, so if I have 2 `Task`s with the same name, the linter can't decide which definition to use:

```yaml
---
# foo/task.yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: my-task
spec:
  params:
    - name: foo
  steps: []

---
# bar/task.yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: my-task
spec:
  params:
    - name: bar
  steps: []

---
# baz/pipeline.yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: my-pipeline
spec:
  tasks:
    - name: my-task
      taskRef:
        name: my-task
      params:
        - name: foo # this is a valid parameter with foo/task.yaml, but invalid with bar/task.yaml
          value: something
```

The linter _could_ use some heuristics to infer which one is the right task, but I don't think that this would be very accurate.

I think it'd make sense to support the scenario you mentioned by specifying "groups" of definitions. see #8

I'll close this, as there's an existing workaround that @necccc mentioned, the only trick is that the rule has a different name (`no-duplicate-resource` instead of `no-resource-redefine`):

```yaml
---
rules:
  no-duplicate-resource: off
```
