### ISSUE TITLE
Workspaces defined on Tasks in a Pipeline assume workspace field

### ISSUE THREAD

**Issue by mbwhite** [IBM/tekton-lint#93]
Given this example... it will fail as the workspace defined in the task just uses the `name` field - code is assuming that the `workspace` field is present instead

```
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name:  run-checks
spec:
  params:
  workspaces:
    - name: workspace-checks
  tasks:
    - name: run-checks
      taskRef:
        name: task-run-checks
      workspaces:
        - name: workspace-checks
```

Documentation here indicates that `workspace` is optional
https://tekton.dev/docs/pipelines/pipeline-api/#tekton.dev/v1.WorkspacePipelineTaskBinding

Adjusting the code so that if workspace is specified it must match up with the one defined in the pipeline, if it's not present the name must match up instead.
